@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
<<<<<<< HEAD:lab2/hdl/TRAIN_TOUR/TRAIN_TOUR.sim/sim_1/behav/xsim/compile.bat
REM Generated by Vivado on Sat Jul 15 00:48:24 +0800 2023
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
=======
REM Generated by Vivado on Sun Jul 16 20:31:17 +0800 2023
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
>>>>>>> 16b66e8c7946656f49bfb98077c16759900e5334:lab2/hdl/project_1/project_1.sim/sim_1/behav/xsim/compile.bat
REM
REM IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
REM
REM usage: compile.bat
REM
REM ****************************************************************************
REM compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -prj TESTBED_vlog.prj"
call xvlog  --incr --relax -prj TESTBED_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
